name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pipx install poetry

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py